(function(){'use strict';
var root=document.documentElement,reduce=window.matchMedia('(prefers-reduced-motion: reduce)').matches,theme=document.getElementById('theme');
function setTheme(t){root.dataset.theme=t;try{localStorage.setItem('deeporca-theme',t)}catch(e){}}setTheme(root.dataset.theme==='light'?'light':'deep');theme.addEventListener('click',function(){setTheme(root.dataset.theme==='deep'?'light':'deep')});
var scenes=[].slice.call(document.querySelectorAll('.scene')),stops=[].slice.call(document.querySelectorAll('.depth-stops button')),readout=document.getElementById('depth-readout'),depths=['000m|surface','380m|shape','760m|make','1100m|connect','1400m|logbook'],current=0;
function goTo(i){if(i<0||i>=scenes.length)return;current=i;scenes[i].scrollIntoView({behavior:reduce?'auto':'smooth'});stops.forEach(function(s,n){s.classList.toggle('active',n===i)});var p=depths[i].split('|');readout.innerHTML=p[0]+'<br><small>'+p[1]+'</small>'}
stops.forEach(function(s){s.addEventListener('click',function(){goTo(Number(s.dataset.go))})});document.getElementById('enter-dive').addEventListener('click',function(){goTo(1)});
if(!reduce){var io=new IntersectionObserver(function(entries){entries.forEach(function(e){if(e.isIntersecting){var i=scenes.indexOf(e.target);if(i>-1){current=i;stops.forEach(function(s,n){s.classList.toggle('active',n===i)});var p=depths[i].split('|');readout.innerHTML=p[0]+'<br><small>'+p[1]+'</small>'}e.target.classList.add('seen')}})},{threshold:.55});scenes.forEach(function(s){io.observe(s)})}else scenes.forEach(function(s){s.classList.add('seen')});
window.addEventListener('keydown',function(e){var tag=document.activeElement&&document.activeElement.tagName;if(['INPUT','TEXTAREA','SELECT'].indexOf(tag)>-1||document.activeElement&&document.activeElement.isContentEditable)return;if(['ArrowDown','PageDown'].indexOf(e.key)>-1){e.preventDefault();goTo(Math.min(current+1,scenes.length-1))}if(['ArrowUp','PageUp'].indexOf(e.key)>-1){e.preventDefault();goTo(Math.max(current-1,0))}if(e.key==='Enter'&&current===0&&document.activeElement===document.body)document.getElementById('wake-signal').click()});
/* Surface sonar wake */
var surface=document.getElementById('surface'),wake=document.getElementById('wake-signal'),surfaceStatus=document.getElementById('surface-status'),wakeLabel=document.getElementById('wake-label'),echo=document.getElementById('echo-particles'),wakeCount=0;
function seedEcho(){echo.innerHTML='';for(var i=0;i<22;i++){var p=document.createElement('i');p.className='echo-particle';var a=(Math.PI*2*i)/22,r=80+Math.random()*180;p.style.left='calc(75% + '+Math.cos(a)*r+'px)';p.style.top='calc(47% + '+Math.sin(a)*r+'px)';p.style.setProperty('--dx',Math.cos(a)*r+'px');p.style.setProperty('--dy',Math.sin(a)*r+'px');p.style.animationDelay=(i*18)+'ms';echo.appendChild(p)}}
function wakeWhale(){wakeCount++;surface.classList.remove('surface-echo');void surface.offsetWidth;surface.classList.add('surface-awake');seedEcho();surfaceStatus.textContent=wakeCount>=3?'ECHO LOCKED / POD SIGNAL ACQUIRED':'SIGNAL ACQUIRED / DEEPORCA IS LISTENING';wakeLabel.innerHTML=wakeCount>=3?'POD ECHO<br>RECEIVED':'SIGNAL RECEIVED<br>YOUR IDEA IS HEARD';wake.setAttribute('aria-pressed','true');if(wakeCount>=3){surface.classList.add('surface-echo');surfaceStatus.textContent='POD ECHO / 3 SIGNALS RETURNED'}}wake.addEventListener('click',wakeWhale);
/* Shape synthesis */
var phaseData=[['01 / INTENT','一句需求，先被真正听见','用自然语言描述你的流程，DeepOrca 从意图开始理解，而不是从一堆选项开始。'],['02 / PROTOTYPE','流程开始呼吸','低保真原型快速成形，关键动作被看见、被点击、被验证。'],['03 / DESIGN','视觉长出秩序','设计系统、色彩和层级沿着意图展开，成为可以独立交付的设计语言。'],['04 / CODE','想法真正运行','代码、变更与上下文连进同一个 Agent 循环，让结果不止停在画布上。']],phaseButtons=[].slice.call(document.querySelectorAll('[data-phase]')),parts=[].slice.call(document.querySelectorAll('.phase-part')),phaseNo=document.getElementById('phase-no'),phaseTitle=document.getElementById('phase-title'),phaseText=document.getElementById('phase-text'),particles=document.getElementById('synthesis-particles'),phaseIndex=0,phaseTimer=null;
function seedSynthesis(i){particles.innerHTML='';for(var n=0;n<28;n++){var p=document.createElement('i');p.className='synthesis-particle'+(n%7===0?' hot':'');var angle=n*.9+i*.35,rad=25+(n%8)*8;p.style.left=(50+Math.cos(angle)*rad)+'%';p.style.top=(38+Math.sin(angle)*rad)+'%';p.style.transform='translate('+Math.cos(angle+i)*((i+1)*7)+'px,'+Math.sin(angle-i)*((i+1)*5)+'px) scale('+(i===3?1.4:1)+')';p.style.opacity=(.35+(n%5)*.12);particles.appendChild(p)}}
function renderPhase(i){phaseIndex=i;phaseButtons.forEach(function(b,n){b.classList.toggle('active',n===i);b.setAttribute('role','tab');b.setAttribute('aria-selected',String(n===i));b.setAttribute('aria-controls','morph-stage')});parts.forEach(function(p,n){p.classList.toggle('show',n===i)});phaseNo.textContent=phaseData[i][0];phaseTitle.textContent=phaseData[i][1];phaseText.textContent=phaseData[i][2];seedSynthesis(i)}
function stopPhase(){clearInterval(phaseTimer);phaseTimer=null;document.getElementById('replay-phase').textContent='重放转化 ↻'}function replayPhase(){stopPhase();var i=0;renderPhase(i);if(reduce)return;document.getElementById('replay-phase').textContent='转化中…';phaseTimer=setInterval(function(){i++;if(i>3){stopPhase();return}renderPhase(i)},1150)}phaseButtons.forEach(function(b){b.addEventListener('click',function(){stopPhase();renderPhase(Number(b.dataset.phase))})});document.getElementById('replay-phase').addEventListener('click',replayPhase);renderPhase(0);
/* Workbench pods */
var podData={chat:['01 / WORKBENCH','AI 会话工作台','流式会话、工具调用与上下文压缩在同一循环中发生，让任务从一个念头持续长成可接续的工作。'],editor:['02 / WORKBENCH','专业编辑器','把思考直接送进文件；内联差异让每一次 AI 变更都能被接受、拒绝或继续推敲。'],git:['03 / WORKBENCH','Git 源码管理','分支、变更与提交不离开工作台，让每次创作留下清晰的版本航迹。'],wiki:['04 / WORKBENCH','项目索引与 Wiki','从符号、文档和架构三个视角快速理解项目，不必在陌生代码里独自潜行。'],memory:['05 / CORE','本地智能层','本地向量嵌入与长期记忆，让 AI 越用越懂你的项目，数据不出本机。'],security:['06 / CONTROL','权限与安全','敏感操作逐一确认，计划模式先规划后执行，让每次行动都有边界。']},podDetail=document.getElementById('pod-detail');
document.querySelectorAll('[data-pod]').forEach(function(b){b.addEventListener('click',function(){var d=podData[b.dataset.pod];podDetail.innerHTML='<span>'+d[0]+'</span><h3>'+d[1]+'</h3><p>'+d[2]+'</p>';document.querySelectorAll('[data-pod]').forEach(function(x){x.classList.remove('active')});b.classList.add('active');document.getElementById('orbital').style.setProperty('--active-pod',b.dataset.pod)})});document.querySelectorAll('[data-orbit]').forEach(function(b){b.addEventListener('click',function(){document.querySelectorAll('[data-orbit]').forEach(function(x){x.classList.remove('active')});b.classList.add('active');document.getElementById('orbital').classList.toggle('show-extend',b.dataset.orbit==='extend')})});
/* Relay state machine */
var relay=document.getElementById('relay'),sea=document.querySelector('.relay-sea'),token=document.getElementById('relay-token'),target=document.getElementById('device-b'),instruction=document.getElementById('relay-instruction'),audit=document.getElementById('audit-card'),burst=document.getElementById('handoff-burst'),events=[['同主题验证','发现 Orca / B：同一局域网，同一工作区主题。发现不等于共享。'],['共享范围','只选择需求、原型与任务记录进入这次协作。边界由 A 掌控。'],['多方签名','device:A 与 device:B 为记录签名，来源与时间被一并保存。'],['上下文注入','B 收到的不只是一条消息，还有关联原型、设计与对话上下文。'],['接续执行','任务在 B 设备继续运行，新的结果沿同一条链留下记录。']],eventButtons=[].slice.call(document.querySelectorAll('[data-event]')),relayIndex=0,relayTimer=null,relayPlaying=false,relayVisible=false,dragging=false,dragMove=null,dragEnd=null;
function showRelay(i){relayIndex=i;eventButtons.forEach(function(b,n){b.classList.toggle('active',n===i)});audit.innerHTML='<span>EVENT '+String(i+1).padStart(2,'0')+'</span><h3>'+events[i][0]+'</h3><p>'+events[i][1]+'</p>';token.className='relay-token relay-'+i;token.style.left='';token.style.top='';token.setAttribute('aria-grabbed','false');relay.classList.toggle('handoff-complete',i===4);if(i===4){instruction.childNodes[0].textContent='接力完成：Orca / B 正在继续执行';burst.setAttribute('aria-hidden','false')}else{instruction.childNodes[0].textContent=i===3?'上下文已注入 Orca / B':'按住任务信号，拖到 Orca / B';burst.setAttribute('aria-hidden','true')}}
function stopRelay(){relayPlaying=false;clearInterval(relayTimer);relayTimer=null;document.getElementById('relay-auto').textContent=reduce?'自动演示不可用':'继续自动演示'}function startRelay(){if(reduce)return;relayPlaying=true;document.getElementById('relay-auto').textContent='暂停自动演示';clearInterval(relayTimer);relayTimer=setInterval(function(){showRelay((relayIndex+1)%events.length)},2800)}
function handoff(){showRelay(4);stopRelay();instruction.childNodes[0].textContent='接力完成：Orca / B 正在继续执行'}eventButtons.forEach(function(b){b.addEventListener('click',function(){showRelay(Number(b.dataset.event));stopRelay()})});document.getElementById('relay-auto').addEventListener('click',function(){relayPlaying?stopRelay():startRelay()});document.getElementById('relay-reset').addEventListener('click',function(){showRelay(0);startRelay()});token.addEventListener('keydown',function(e){if(e.key==='Enter'||e.key===' '){e.preventDefault();handoff()}});
function endDrag(e){if(!dragging)return;dragging=false;token.classList.remove('dragging');token.setPointerCapture&&token.releasePointerCapture(e.pointerId);sea.removeEventListener('pointermove',dragMove);sea.removeEventListener('pointerup',dragEnd);sea.removeEventListener('pointercancel',dragEnd);token.setAttribute('aria-grabbed','false');var tr=target.getBoundingClientRect();if(e.clientX>tr.left-45&&e.clientX<tr.right+45&&e.clientY>tr.top-50&&e.clientY<tr.bottom+50)handoff();else{token.style.left='';token.style.top='';showRelay(relayIndex)}}
function moveDrag(e){if(!dragging)return;var r=sea.getBoundingClientRect();token.style.left=Math.max(3,Math.min(83,(e.clientX-r.left)/r.width*100-8))+'%';token.style.top=Math.max(8,Math.min(76,(e.clientY-r.top)/r.height*100-6))+'%'}
token.addEventListener('pointerdown',function(e){if(e.button!==undefined&&e.button!==0)return;stopRelay();dragging=true;token.setPointerCapture&&token.setPointerCapture(e.pointerId);token.classList.add('dragging');token.setAttribute('aria-grabbed','true');dragMove=moveDrag;dragEnd=endDrag;sea.addEventListener('pointermove',dragMove);sea.addEventListener('pointerup',dragEnd);sea.addEventListener('pointercancel',dragEnd)});
var relayObserver=new IntersectionObserver(function(entries){entries.forEach(function(e){relayVisible=e.isIntersecting;if(relayVisible&&!reduce&&!relayPlaying)startRelay();if(!relayVisible&&relayPlaying)stopRelay()})},{threshold:.35});relayObserver.observe(relay);showRelay(0);
})();