// AUTO-GENERATED by build.mjs — do not edit manually.
// This placeholder is checked in so `tsc --noEmit` works on a fresh clone
// before the first build. The `desktop:build` step overwrites this file with
// the actual vendored Tailwind JIT script (~400KB string).
export default "";
