/**
 * Review HTML report generator — the delegated review's presentation surface
 * (user ask 2026-08-31: 审查结果以 HTML 报告渲染到专属工作区，而不是直接在
 * 侧栏展示). Pure string builder: self-contained document (inline CSS, auto
 * light/dark via prefers-color-scheme), findings grouped by file with
 * severity chips, CRG risk annotations, and COMPLETE HTML escaping of every
 * model-authored string (content/path/snippets are LLM output — escape
 * everything, render nothing raw).
 */

export interface ReviewReportInput {
  /** Reviewed repository root (shown as the project identity). */
  readonly root: string;
  /** Display name for the header (usually the repo folder name). */
  readonly projectName: string;
  readonly status: string;
  readonly statusNote: string;
  readonly generatedAtIso: string;
  readonly language: string;
  /** Pre-localized scope label (caller owns localization). */
  readonly modeLabel: string;
  readonly summary?: {
    filesReviewed?: number;
    comments?: number;
    excludedByPolicy?: number;
    unsupportedFiles?: number;
  };
  /** Merged findings (delegation comments; may carry a `crgRisk` annotation). */
  readonly comments: ReadonlyArray<Record<string, unknown>>;
}

type Severity = "critical" | "high" | "medium" | "low";

interface ParsedFinding {
  severity: Severity | null;
  text: string;
}

function escapeHtml(value: string): string {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

/** Split the delegated `[SEVERITY] rest` content prefix (host contract). */
function parseFinding(content: string): ParsedFinding {
  const m = content.match(/^\[(CRITICAL|HIGH|MEDIUM|LOW)\]\s*([\s\S]*)$/);
  if (!m) return { severity: null, text: content };
  return { severity: m[1].toLowerCase() as ParsedFinding["severity"], text: m[2] };
}

function severityChip(severity: ParsedFinding["severity"], labels: Record<string, string>): string {
  if (!severity) return "";
  const label = labels[severity] ?? severity.toUpperCase();
  return `<span class="chip sev-${severity}">${escapeHtml(label)}</span>`;
}

function str(record: Record<string, unknown>, key: string): string {
  const value = record[key];
  return typeof value === "string" ? value : value == null ? "" : String(value);
}

export function buildReviewReportHtml(input: ReviewReportInput): string {
  const zh = input.language.toLowerCase().startsWith("zh");
  const labels = zh
    ? {
        title: "代码审查报告",
        project: "项目",
        mode: "范围",
        generated: "生成时间",
        files: "审查文件",
        findings: "审查意见",
        excluded: "策略排除",
        excludedNote: "以上变更全部按策略排除（生成物 / 点路径）或不支持审查该文件类型，因此本次没有可审查内容。",
        noFindings: "未发现需要报告的问题。",
        crgRisk: "CRG 风险",
        suggestion: "建议",
        existing: "现状",
        status: "状态",
        generatedBy: "由 DeepOrca 委托审查管线生成（OCR 选文件与规则，内置模型逐文件审查）",
      }
    : {
        title: "Code Review Report",
        project: "Project",
        mode: "Scope",
        generated: "Generated",
        files: "Files reviewed",
        findings: "Findings",
        excluded: "Excluded",
        excludedNote:
          "Every change was excluded by policy (generated / dot-paths) or has an unsupported type — nothing was reviewable this run.",
        noFindings: "No findings worth reporting.",
        crgRisk: "CRG risk",
        suggestion: "Suggestion",
        existing: "Current",
        status: "Status",
        generatedBy:
          "Generated by the DeepOrca delegation pipeline (OCR selects files & rules; the built-in model reviews).",
      };

  const byFile = new Map<string, Record<string, unknown>[]>();
  for (const comment of input.comments) {
    const file = str(comment, "path") || (zh ? "（未标注文件）" : "(no path)");
    const list = byFile.get(file) ?? [];
    list.push(comment);
    byFile.set(file, list);
  }

  const sections = [...byFile.entries()]
    .map(([file, findings]) => {
      const cards = findings
        .map((finding) => {
          const { severity, text } = parseFinding(str(finding, "content"));
          const existing = str(finding, "existingCode") || str(finding, "existing_code");
          const suggestion = str(finding, "suggestionCode") || str(finding, "suggestion_code");
          const crgRisk = str(finding, "crgRisk");
          const startLine = Number(finding.startLine ?? finding.start_line ?? 0);
          const endLine = Number(finding.endLine ?? finding.end_line ?? 0);
          const lineLabel = startLine > 0 ? `:${startLine}${endLine > startLine ? `-${endLine}` : ""}` : "";
          return [
            `<div class="finding">`,
            `<div class="finding-head">${severityChip(severity, labels)}<span class="loc">${escapeHtml(file)}${escapeHtml(lineLabel)}</span>${crgRisk ? `<span class="chip crg">${escapeHtml(labels.crgRisk)}: ${escapeHtml(crgRisk)}</span>` : ""}</div>`,
            `<div class="finding-body">${escapeHtml(text)}</div>`,
            existing ? `<pre class="code existing">${escapeHtml(existing)}</pre>` : "",
            suggestion
              ? `<div class="suggestion-label">${escapeHtml(labels.suggestion)}</div><pre class="code suggestion">${escapeHtml(suggestion)}</pre>`
              : "",
            `</div>`,
          ]
            .filter(Boolean)
            .join("\n");
        })
        .join("\n");
      return `<section class="file"><h2><code>${escapeHtml(file)}</code> <span class="count">${findings.length}</span></h2>${cards}</section>`;
    })
    .join("\n");

  const findingsBody = input.comments.length > 0 ? sections : `<p class="empty">${escapeHtml(labels.noFindings)}</p>`;

  const statusKey = `status.${input.status}`;
  const statusText = zh
    ? ({
        "status.success": "成功",
        "status.completed_with_warnings": "完成（有警告）",
        "status.completed_with_errors": "完成（有错误）",
        "status.skipped": "已跳过",
      }[statusKey] ?? input.status)
    : input.status;

  const generatedLocal = new Date(input.generatedAtIso).toLocaleString(zh ? "zh-CN" : "en-US", { hour12: false });
  // unsupportedFiles ⊆ excludedByPolicy (review round 2026-09-01) — summing
  // the two double-counted every unsupported file in this card and note.
  const excludedCount = input.summary?.excludedByPolicy ?? 0;

  return `<!DOCTYPE html>
<html lang="${escapeHtml(input.language)}">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${escapeHtml(labels.title)} — ${escapeHtml(input.projectName)}</title>
<style>
  :root { color-scheme: light dark; }
  * { box-sizing: border-box; }
  body {
    margin: 0; padding: 32px 40px 64px; font-family: -apple-system, BlinkMacSystemFont,
    "Segoe UI", Roboto, "PingFang SC", "Microsoft YaHei", sans-serif;
    background: #f4f6fa; color: #1b2129; line-height: 1.6;
  }
  @media (prefers-color-scheme: dark) {
    body { background: #17191f; color: #e6e9ef; }
    .file { background: #1f2229 !important; border-color: #34383f !important; }
    .finding { background: #23262e !important; border-color: #3a3f48 !important; }
    .meta { color: #9aa5b3 !important; }
    code { background: #2b2e34 !important; }
    pre.code { background: #26292f !important; }
    h2 code { color: #e6e9ef !important; }
  }
  h1 { font-size: 22px; margin: 0 0 4px; }
  .meta { color: #66707d; font-size: 13px; margin-bottom: 20px; }
  .cards { display: flex; gap: 14px; margin: 0 0 26px; flex-wrap: wrap; }
  .card { background: #fff; border: 1px solid #d9dee6; border-radius: 10px; padding: 12px 20px; min-width: 130px; }
  .card .num { font-size: 24px; font-weight: 650; }
  .card .label { font-size: 12px; color: #66707d; }
  .file { background: #fff; border: 1px solid #d9dee6; border-radius: 12px; padding: 18px 22px; margin-bottom: 18px; }
  .file h2 { font-size: 15px; margin: 0 0 12px; display: flex; align-items: center; gap: 8px; }
  .file h2 code { background: #eceff3; border-radius: 6px; padding: 2px 8px; font-size: 13px; color: #1b2129; }
  .count { font-size: 12px; color: #66707d; }
  .finding { border: 1px solid #e2e6ec; border-radius: 9px; padding: 12px 14px; margin: 10px 0; background: #fbfcfd; }
  .finding-head { display: flex; align-items: center; gap: 8px; flex-wrap: wrap; margin-bottom: 6px; }
  .loc { font-family: ui-monospace, Consolas, monospace; font-size: 12.5px; color: #55606d; }
  .chip { font-size: 11px; font-weight: 650; padding: 1px 8px; border-radius: 999px; letter-spacing: 0.3px; }
  .sev-critical { background: #7f1d1d; color: #fff; }
  .sev-high { background: #c2410c; color: #fff; }
  .sev-medium { background: #b45309; color: #fff; }
  .sev-low { background: #64748b; color: #fff; }
  .chip.crg { background: rgba(28,111,224,0.12); color: #1c6fe0; }
  .finding-body { white-space: pre-wrap; }
  pre.code { font-family: ui-monospace, Consolas, monospace; font-size: 12.5px; border-radius: 8px; padding: 10px 12px; overflow-x: auto; white-space: pre-wrap; margin: 8px 0 0; }
  pre.existing { background: rgba(209,69,59,0.08); border: 1px solid rgba(209,69,59,0.25); }
  pre.suggestion { background: rgba(47,158,68,0.08); border: 1px solid rgba(47,158,68,0.25); }
  .suggestion-label { font-size: 12px; color: #2f9e44; margin-top: 8px; }
  .empty { color: #55606d; background: #fff; border: 1px dashed #c3cdd9; border-radius: 12px; padding: 20px; text-align: center; }
  .empty-note { color: #b45309; background: rgba(217, 119, 6, 0.07); border: 1px solid rgba(217, 119, 6, 0.3);
    border-radius: 10px; padding: 12px 16px; font-size: 13px; }
  .card.excluded { border-color: rgba(217, 119, 6, 0.45); }
  @media (prefers-color-scheme: dark) {
    .empty-note { color: #fbbf24 !important; background: rgba(217, 119, 6, 0.12) !important; border-color: rgba(217, 119, 6, 0.4) !important; }
    .card.excluded { border-color: rgba(217, 119, 6, 0.5) !important; }
  }
  .footer { margin-top: 34px; font-size: 12px; color: #8590a0; }
</style>
</head>
<body>
<h1>${escapeHtml(labels.title)} — ${escapeHtml(input.projectName)}</h1>
<div class="meta">
  ${escapeHtml(labels.project)}: <code>${escapeHtml(input.root)}</code> ·
  ${escapeHtml(labels.mode)}: ${escapeHtml(input.modeLabel)} ·
  ${escapeHtml(labels.generated)}: ${escapeHtml(generatedLocal)} ·
  ${escapeHtml(labels.status)}: ${escapeHtml(statusText)}
</div>
<div class="cards">
  <div class="card"><div class="num">${input.summary?.filesReviewed ?? 0}</div><div class="label">${escapeHtml(labels.files)}</div></div>
  <div class="card"><div class="num">${input.comments.length}</div><div class="label">${escapeHtml(labels.findings)}</div></div>
  ${
    excludedCount > 0
      ? `<div class="card excluded"><div class="num">${excludedCount}</div><div class="label">${escapeHtml(labels.excluded)}</div></div>`
      : ""
  }
</div>
${excludedCount > 0 && (input.summary?.filesReviewed ?? 0) === 0 ? `<p class="empty-note">${escapeHtml(labels.excludedNote)}</p>` : ""}
${findingsBody}
<p class="footer">${escapeHtml(labels.generatedBy)} · ${escapeHtml(input.statusNote)}</p>
</body>
</html>`;
}
